[package]
name = "leptos-wasi-wasip2-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.93.0"
publish = false

[dependencies]
leptos_wasi = { package = "leptos-wasi-runtime", path = "../../..", default-features = false, features = ["wasip2"] }
leptos = { version = "0.8.20", default-features = false, features = ["ssr"] }
server_fn = { version = "0.8.12", default-features = false, features = ["axum-no-default"] }
serde = { version = "1", features = ["derive"] }
