spin_manifest_version = 2

[application]
name = "spin-counter"
version = "0.1.0"
authors = ["Uriah Galang <codeitlikemiley@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-counter"

[component.spin-counter]
source = "target/wasm32-wasip1/release/spin_counter.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.spin-counter.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=spin_counter cargo build --lib --target wasm32-wasip1 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "spin-counter-pkg"

[component.spin-counter-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.1.0/spin_static_fs.wasm", digest = "sha256:96c76d9af86420b39eb6cd7be5550e3cb5d4cc4de572ce0fd1f6a29471536cb4" }
files = [{ source = "target/site/pkg", destination = "/" }]
