[package]
name = "leptos-wasi-wasip3-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.93.0"
publish = false

[dependencies]
leptos_wasi = { package = "leptos-wasi-runtime", path = "../../..", default-features = false, features = ["wasip3"] }
http = "1.4.1"
wasip3 = { version = "=0.7.0", features = ["http-compat"] }
