[package]
name = "leptos-wasi-dual-runtime-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.93.0"
publish = false

[dependencies]
leptos_wasi = { package = "leptos-wasi-runtime", path = "../../..", default-features = false, features = ["wasip2", "wasip3", "islands-router"] }
http = "1.4.1"
wasip3 = { version = "=0.7.1", features = ["http-compat"] }
leptos = { version = "0.8.20", default-features = false, features = ["ssr"] }
server_fn = { version = "0.8.12", default-features = false, features = ["axum-no-default"] }
serde = { version = "1", features = ["derive"] }
