[package]
name = "leptos-wasi-dual-runtime-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.93.0"
publish = false

[dependencies]
leptos_wasi = { path = "../../..", default-features = false, features = ["wasip2", "wasip3", "islands-router"] }
http = "1.4.1"
wasip3 = { version = "0.6.0", features = ["http-compat"] }
