[package]
name = "leptos-wasi-middleware-fixture"
version = "0.0.0"
edition = "2024"
rust-version = "1.93.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = { git = "https://github.com/spinframework/spin-rust-sdk", rev = "14e675aa877c2dd4040c631421dfdaf5d526fb40", default-features = false, features = ["http", "http-middleware"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[workspace]
