#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DURATION="${DURATION:-600}"
CONCURRENCY="${CONCURRENCY:-100}"
HOST="${HOST:-wasmtime}"
AUTHENTICATION_MODE=trusted_ingress AUTHZ=1 MIDDLEWARE=0 HOST="$HOST" \
  AUTHZ_FULL_CHAIN_BENCHMARK_ONLY=1 AUTHZ_FULL_CHAIN_SOAK=1 \
  TRUSTED_INGRESS_HEALTH_CHECKS=0 \
  AUTHZ_FULL_CHAIN_SOAK_DURATION="$DURATION" \
  AUTHZ_FULL_CHAIN_BENCHMARK_CONCURRENCY="$CONCURRENCY" \
  "$ROOT/scripts/run-trusted-ingress-browser.sh"
