name: CI

env:
  CARGO_TERM_COLOR: always

on:
  push:
    branches:
      - main
  pull_requests:
    branches:
      - main

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run CI
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: ci-flow
